/**
 * Created by rafa on 09/04/2017.
 */
var mongoose = require('mongoose');
mongoose.Promise = global.Promise


var Schema = mongoose.Schema;


var Candidate = new Schema({
  'general_name' : { type: String, default: null},
  'general_middle_name' : { type: String, default: null},
  'general_surname' : { type: String, default: null},
  'general_sex' : { type: String, default: null},
  'general_birthday' : { type: String, default: null},
  'general_birth_place' : { type: String, default: null},
  'general_nationality' : { type: String, default: null},
  'personal_work_conditions' : { type: String, default: null},
  'personal_experience' : { type: String, default: null},
  'personal_house_phone' : { type: String, default: null},
  'personal_phone' : { type: String, default: null},
  'personal_email' : { type: String, default: null},
  'personal_education_level' : { type: String, default: null},
  'personal_life_place' : { type: String, default: null},
  'personal_can_move' : { type: String, default: null},
  'personal_photo' : { type: String, default: null},
  'personal_cv' : { type: String, default: null},
  'personal_can_trips' : { type: String, default: null},
  'education_name' : { type: String, default: null},
  'education_faculty' : { type: String, default: null},
  'education_specialty' : { type: String, default: null},
  'education_ball' : { type: String, default: null},
  'education_start' : { type: String, default: null},
  'education_end' : { type: String, default: null},
  'education_form' : { type: String, default: null},
  'education_kazakh' : { type: String, default: null},
  'education_russian' : { type: String, default: null},
  'education_english' : { type: String, default: null},
  'education_other' : { type: String, default: null},
  'lastwork_name' : { type: String, default: null},
  'lastwork_position' : { type: String, default: null},
  'lastwork_salary' : { type: String, default: null},
  'lastwork_start' : { type: String, default: null},
  'lastwork_end' : { type: String, default: null},
  'lastwork_rating' : { type: String, default: null},
  'lastwork_duties' : { type: String, default: null},
  'lastwork__end_reason' : { type: String, default: null},
  'lastwork_reference_person' : { type: String, default: null},
  'lastwork_reference_person_position' : { type: String, default: null},
  'lastwork_reference_person_phone' : { type: String, default: null},
  'summery_desired_salary' : { type: String, default: null},
  'summery_where_find_us' : { type: String, default: null},
  'summery_when_can_start_work' : { type: String, default: null},
  'summery_fb' : { type: String, default: null},
  'summery_insta' : { type: String, default: null},
  'summery_vk' : { type: String, default: null},
  'summery_interview_type' : { type: String, default: null},
  'summery_take_important' : { type: String, default: null},
  'summery_family' : { type: String, default: null},
  'summery_car' : { type: String, default: null},
  'summery_question' : { type: String, default: null},
  'summery_additional' : { type: String, default: null},
  'summery_certificates' : { type: String, default: null},
  'interview_day' : { type: String, default: null},
  'interview_time' : { type: String, default: null},
  'vacancy_id' : { type: String, default: null},
  'megaplan': { type: Number, default: null}, // poroli
  'one_c': { type: Number, default: null},// poroli
  'computer': { type: Number, default: null},// poroli
  'guest_id': {type: String},
  'employee_id': {type: String, unique: true},
  'admin' : { type: Boolean, default: false }, // admin flag,
  'bot_id': {type: String, unique: true},
  'department': {type: String}
});


module.exports = mongoose.model('Candidate', Candidate);


/*
*
*
* 'general_name' : general_name,
 'general_middle_name' : general_middle_name,
 'general_surname' : general_surname,
 'general_sex' : general_sex,
 'general_birthday' : general_birthday,
 'general_birth_place' : general_birth_place,
 'general_nationality' : general_nationality,
 'personal_work_conditions' : personal_work_conditions,
 'personal_experience' : personal_experience,
 'personal_house_phone' : personal_house_phone,
 'personal_phone' : personal_phone,
 'personal_email' : personal_email,
 'personal_education_level' : personal_education_level,
 'personal_life_place' : personal_life_place,
 'personal_can_move' : personal_can_move,
 'personal_photo' : personal_photo,
 'personal_cv' : personal_cv,
 'personal_can_trips' : personal_can_trips,
 'education_name' : education_name,
 'education_faculty' : education_faculty,
 'education_specialty' : education_specialty,
 'education_ball' : education_ball,
 'education_start' : education_start,
 'education_end' : education_end,
 'education_form' : education_form,
 'education_kazakh' : education_kazakh,
 'education_russian' : education_russian,
 'education_english' : education_english,
 'education_other' : education_other,
 'lastwork_name' : lastwork_name,
 'lastwork_position' : lastwork_position,
 'lastwork_salary' : lastwork_salary,
 'lastwork_start' : lastwork_start,
 'lastwork_end' : lastwork_end,
 'lastwork_rating' : lastwork_rating,
 'lastwork_duties' : lastwork_duties,
 'lastwork__end_reason' : lastwork__end_reason,
 'lastwork_reference_person' : lastwork_reference_person,
 'lastwork_reference_person_position' : lastwork_reference_person_position,
 'lastwork_reference_person_phone' : lastwork_reference_person_phone,
 'summery_desired_salary' : summery_desired_salary,
 'summery_where_find_us' : summery_where_find_us,
 'summery_when_can_start_work' : summery_when_can_start_work,
 'summery_fb' : summery_fb,
 'summery_insta' : summery_insta,
 'summery_vk' : summery_vk,
 'summery_interview_type' : summery_interview_type,
 'summery_take_important' : summery_take_important,
 'summery_family' : summery_family,
 'summery_car' : summery_car,
 'summery_question' : summery_question,
 'summery_additional' : summery_additional,
 'summery_certificates' : summery_certificates,
 'interview_day' : interview_day,
 'interview_time' : interview_time,
 'vacancy_id' : '<?php echo $_GET['vacancy_id'] ?>'
*
* */